function send_engine_state_to_ecu(client_socket, state_data)
  
  # Determine valve status text
  if (state_data.starterValveOpen)
    valve_status = "OPEN";
  else
    valve_status = "CLOSED";
  endif
  
  msg = sprintf([...
    "=== ENGINE STATE ===\n" ...
    "Time= %.2f s\n" ...
    "Engine Speed= %.0f RPM\n" ...
    "Net Torque= %.2f N·m\n" ...
    "Starter Torque= %.2f N·m\n" ...
    "Compressor Outlet Pressure= %.0f Pa\n" ...
    "Compressor Outlet Temperature= %.1f K\n" ...
    "Mass Flow Rate= %.2f kg/s\n" ...
    "Starter Valve= %s\n" ...
    "==================\n"], ...
    state_data.time, ...
    state_data.N, ...
    state_data.T_net, ...
    state_data.T_starter, ...
    state_data.P0_out, ...
    state_data.T0_out, ...
    state_data.m_dot, ...
    valve_status);
  
  send(client_socket, msg);
endfunction